# Site Information
site_name: Freenalytics
site_description: An open source, self-hosted dashboard for usage analytics of general use applications.
site_author: Freenalytics
site_url: https://freenalytics.github.io

# Repo
repo_name: freenalytics/freenalytics
repo_url: https://github.com/freenalytics/freenalytics
edit_uri: ''

# Extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/freenalytics
      name: Freenalytics on GitHub
    - icon: fontawesome/brands/docker
      link: https://github.com/freenalytics/freenalytics/pkgs/container/freenalytics
      name: Docker Image
    - icon: fontawesome/solid/code
      link: https://freenalytics.github.io/api-docs/
      name: API Reference
    - icon: fontawesome/brands/trello
      link: https://trello.com/b/oDg8aD7n
      name: Trello Board
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/moonstar_x99
      name: Twitter Profile
  
# Copyright
copyright: Copyright &copy; 2022 Freenalytics

# Theme Customization
theme:
  name: material
  palette:
    - scheme: default
      primary: deep orange
      accent: blue
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: deep orange
      accent: blue
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/git-alt
    logo: fontawesome/solid/chart-line
  language: en
  direction: ltr
  favicon: assets/logo.png
  features:
    - navigation.top
    - navigation.tabs
    - navigation.tracking
    - navigation.expand
    - search.suggest
    - search.highlight

# Extensions
markdown_extensions:
  - admonition
  - meta
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.mark
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.betterem
  - pymdownx.highlight
  - pymdownx.superfences

# Plugins
plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: date

# Navigation
nav:
  - Home: index.md
  - Getting Started:
    - Introduction: getting-started/index.md
    - Hosting with Docker: getting-started/docker-hosting.md
    - Hosting with Node.js: getting-started/node-hosting.md
    - Creating your First Application: getting-started/creating-your-first-application.md
    - Uploading Data: getting-started/uploading-data.md
    - Exporting Data: getting-started/exporting-data.md
  - Reference:
    - Introduction: reference/index.md
    - Application: reference/application.md
    - Schema: reference/schema.md
    - Connector: reference/connector.md
    - Data Entries: reference/data-entries.md
    - API Reference: https://freenalytics.github.io/api-docs/
  - Official Templates:
    - Introduction: official-templates/index.md
    - Official Web Template: official-templates/web-template.md
  - Development:
    - Introduction: development/index.md
    - Web Dashboard: development/web-dashboard.md
    - Server: development/server.md
